import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'horse-racing:language';
const DEFAULT_LANGUAGE = 'vi';

const translations = {
  vi: {
    wallet: 'Ví',
    walletDescription: 'Số dư và nạp tiền',
    walletAccess: 'Quyền truy cập ví',
    walletAccessDenied: 'Không có quyền truy cập',
    walletTopupsUnavailable: 'Tài khoản này không thể sử dụng chức năng nạp ví.',
    walletCurrentBalance: 'Số dư hiện tại',
    walletBalanceDescription: 'Theo dõi số dư ví cho tài khoản {{role}} này.',
    walletGenericUser: 'người dùng',
    walletBalance: 'Số dư',
    walletTopUp: 'Nạp tiền',
    walletTopUpWithProvider: 'Nạp tiền qua {{provider}}',
    walletEnterTopUpAmount: 'Nhập số tiền nạp',
    walletPaymentThroughProvider: 'Thanh toán sẽ được xử lý qua {{provider}}.',
    walletAmount: 'Số tiền',
    walletEnterAmount: 'Nhập số tiền',
    walletPaymentMethod: 'Phương thức thanh toán',
    walletTotal: 'Tổng cộng',
    walletRedirecting: 'Đang chuyển hướng...',
    walletTopUpSuccessful: 'Nạp tiền thành công.',
    walletTopUpFailed: 'Nạp tiền thất bại.',
    walletLoadError: 'Không thể tải thông tin ví.',
    walletAmountGreaterThanZero: 'Số tiền phải lớn hơn 0.',
    walletNoPaymentUrl: 'Giao dịch nạp tiền đã được tạo nhưng không nhận được URL thanh toán.',
    walletCreateTopUpError: 'Không thể tạo giao dịch nạp tiền.',
    close: 'Đóng',
    loading: 'Đang tải',
    languageLabel: 'Ngôn ngữ',
    vietnamese: 'Tiếng Việt',
    english: 'English',
    adminCenter: 'Trung tâm quản trị',
    navigation: 'Điều hướng',
    adminArea: 'Khu vực quản trị',
    signedInAs: 'Đang đăng nhập',
    logout: 'Đăng xuất',
    overview: 'Tổng quan',
    overviewDescription: 'Tình hình vận hành',
    manageUsers: 'Quản lí người dùng',
    usersDescription: 'Tài khoản và vai trò',
    manageOwners: 'Quản lí owner',
    ownersDescription: 'Đơn đăng ký owner',
    tournament: 'Tournament',
    tournamentDescription: 'Sự kiện và Registration',
    manageJockeys: 'Quản lí jockey',
    jockeysDescription: 'Hồ sơ vận động viên',
    manageHorses: 'Quản lí ngựa',
    horsesDescription: 'Hồ sơ và sức khỏe',
    refereeAssignments: 'Phân công Referee',
    refereeDescription: 'Lịch làm việc Referee',
    raceResultReviews: 'Duyệt kết quả Race',
    raceResultReviewDescription: 'Phê duyệt kết quả chính thức',
    operationsCenter: 'Trung tâm điều hành',
    operationsOverview: 'Tổng quan vận hành',
    operationsOverviewSubtitle: 'Theo dõi hồ sơ, chuẩn bị danh sách thi đấu và điều phối các giải đấu từ một màn hình duy nhất.',
    syncing: 'Đang đồng bộ',
    activeAccountCount: '{{count}} tài khoản hoạt động',
    loadingTournaments: 'Đang tải giải đấu',
    tournamentCount: '{{count}} giải đấu',
    retry: 'Thử lại',
    openTournaments: 'Giải đấu đang mở',
    tournamentsInSystem: '{{count}} giải đấu trong hệ thống',
    reviewQueueProfiles: 'Hồ sơ đang chờ xét duyệt',
    reviewQueueProfilesNote: 'Tổng hợp đơn đăng ký, ngựa và jockey',
    raceEntryQueue: 'Đang chờ xếp cuộc đua',
    approvedRegistrationCount: '{{count}} đơn đăng ký đã được duyệt',
    assignedReferees: 'Referee đã phân công',
    assignedRefereesNote: 'Cuộc đua đã có referee phụ trách',
    needsProcessing: 'Cần xử lý',
    adminWorkQueue: 'Hàng chờ công việc quản trị',
    waitingCount: '{{count}} đang chờ',
    ownerApproval: 'Duyệt Owner',
    ownerApprovalNote: 'Tài khoản đang chờ xét duyệt để trở thành Owner',
    registrationApproval: 'Duyệt đơn đăng ký',
    registrationApprovalNote: 'Lời mời jockey đã chấp nhận đang chờ admin quyết định',
    horseApproval: 'Duyệt ngựa',
    horseApprovalNote: 'Hồ sơ ngựa và chứng nhận sức khỏe đang chờ duyệt',
    jockeyApproval: 'Duyệt jockey',
    jockeyApprovalNote: 'Hồ sơ jockey đang chờ phê duyệt',
    raceQueueSetup: 'Hàng chờ xếp cuộc đua',
    raceQueueSetupNote: 'Đơn đăng ký đã xác nhận đang chờ xếp cuộc đua',
    quickActions: 'Thao tác nhanh',
    continueSetup: 'Tiếp tục thiết lập',
    setupTournament: 'Thiết lập giải đấu',
    setupTournamentNote: 'Tạo giải đấu và các cuộc đua trực thuộc',
    refereeAssignmentNote: '{{count}} cuộc đua đã có người phụ trách',
    activeAccountNote: '{{count}} tài khoản đang hoạt động',
    eventSchedule: 'Lịch sự kiện',
    upcomingTournaments: 'Giải đấu sắp diễn ra',
    noUpcomingTournaments: 'Chưa có giải đấu sắp diễn ra',
    noUpcomingTournamentsNote: 'Các giải đấu sắp tới sẽ xuất hiện tại đây.',
    tournamentLifecycle: 'Vòng đời giải đấu',
    tournamentsByStatus: 'Giải đấu theo trạng thái',
    noDate: 'Chưa có ngày',
    notUpdated: 'Chưa cập nhật',
    ownerApplicationsTitle: 'Quản lí owner',
    ownerApplicationsSubtitle: 'Tìm kiếm, lọc, xem xét, duyệt và từ chối đơn đăng ký owner.',
    ownerApplicationDetail: 'Chi tiết đơn đăng ký owner',
    applicationNumber: 'Đơn #{{id}}',
    reviewOwnerApplication: 'Xem thông tin cá nhân đã gửi và duyệt hoặc từ chối yêu cầu owner.',
    backToList: 'Quay lại danh sách',
    personalInformation: 'Thông tin cá nhân',
    submittedDate: 'Đã gửi {{date}}',
    fullName: 'Họ và tên',
    dateOfBirth: 'Ngày sinh',
    gender: 'Giới tính',
    nationality: 'Quốc tịch',
    address: 'Địa chỉ',
    identityDocument: 'Ảnh CMND/CCCD hoặc hộ chiếu',
    identityAlt: 'Ảnh giấy tờ tùy thân của người đăng ký',
    rejectReason: 'Lý do từ chối',
    approve: 'Duyệt',
    reject: 'Từ chối',
    approveOwnerApplication: 'Duyệt đơn đăng ký owner',
    approveOwnerConfirm: 'Bạn có chắc muốn duyệt đơn đăng ký owner này không?',
    rejectOwnerApplication: 'Từ chối đơn đăng ký owner',
    rejectReasonRequired: 'Lý do từ chối là bắt buộc và sẽ hiển thị cho người đăng ký.',
    rejectReasonPlaceholder: 'Ví dụ: Thông tin giấy tờ không hợp lệ.',
    confirmReject: 'Xác nhận từ chối',
    processing: 'Đang xử lý...',
    ownerApplicationsLoadError: 'Không thể tải đơn đăng ký owner.',
    ownerApplicationDetailLoadError: 'Không thể tải chi tiết đơn đăng ký owner.',
    ownerApplicationApproved: 'Đã duyệt đơn đăng ký. Vai trò người dùng đã chuyển thành Owner và hồ sơ owner đã được tạo.',
    ownerApplicationApproveError: 'Không thể duyệt đơn đăng ký owner.',
    ownerApplicationRejected: 'Đã từ chối đơn đăng ký. Vai trò người dùng vẫn là Spectator.',
    ownerApplicationRejectError: 'Không thể từ chối đơn đăng ký owner.',
    noOwnerApplications: 'Không tìm thấy đơn đăng ký owner',
    noOwnerApplicationsHint: 'Hãy thử đổi từ khóa tìm kiếm hoặc bộ lọc trạng thái.',
    searchOwnerApplications: 'Tìm theo ID, người đăng ký, email, ảnh giấy tờ...',
    applicationId: 'Mã đơn',
    applicantName: 'Người đăng ký',
    submissionDate: 'Ngày gửi',
    action: 'Thao tác',
    loadingOwnerApplications: 'Đang tải đơn đăng ký owner...',
    viewDetails: 'Xem chi tiết',
    pageOf: 'Trang {{page}} / {{total}} · {{count}} đơn',
    previous: 'Trước',
    next: 'Sau',
    status_OPEN_FOR_REGISTRATION: 'Đang mở đăng ký',
    status_REGISTRATION_CLOSED: 'Đã đóng đăng ký',
    status_READY: 'Sẵn sàng',
    status_IN_PROGRESS: 'Đang diễn ra',
    status_PENDING_REVIEW: 'Chờ duyệt kết quả',
    status_COMPLETED: 'Đã hoàn thành',
    status_CANCELLED: 'Đã hủy',
    status_ACTIVE: 'Đang hoạt động',
    status_INACTIVE: 'Ngưng hoạt động',
    status_BLOCKED: 'Bị khóa',
    status_PENDING: 'Chờ xử lý',
    status_APPROVED: 'Đã duyệt',
    status_REJECTED: 'Từ chối',
    status_UNDER_REVIEW: 'Đang xét duyệt',
    role_ADMIN: 'Quản trị viên',
    role_OWNER: 'Chủ ngựa',
    role_JOCKEY: 'Nài ngựa',
    role_REFEREE: 'Trọng tài',
    role_SPECTATOR: 'Khán giả',
    admin: 'Quản trị',
    userManagementTitle: 'Quản lý người dùng',
    userManagementSubtitle: 'Quản lý thông tin tài khoản, vai trò và trạng thái truy cập.',
    refresh: 'Làm mới',
    totalUsers: 'Tổng số người dùng',
    activeUsers: 'Đang hoạt động',
    inactiveBlocked: 'Ngưng hoạt động / Bị khóa',
    userList: 'Danh sách người dùng',
    userCount: '{{filtered}} / {{total}} người dùng',
    createUser: 'Tạo người dùng',
    searchUsers: 'Tìm theo tên đăng nhập, email hoặc số điện thoại',
    allRoles: 'Tất cả vai trò',
    allStatuses: 'Tất cả',
    id: 'ID',
    username: 'Tên đăng nhập',
    email: 'Email',
    phone: 'Số điện thoại',
    role: 'Vai trò',
    status: 'Trạng thái',
    actions: 'Thao tác',
    loadingUsers: 'Đang tải người dùng...',
    noUsersFound: 'Không tìm thấy người dùng.',
    edit: 'Chỉnh sửa',
    deactivate: 'Vô hiệu hóa',
    newAccount: 'Tài khoản mới',
    userNumber: 'Người dùng #{{id}}',
    editUser: 'Chỉnh sửa người dùng',
    createUserTitle: 'Tạo người dùng',
    editUserDescription: 'Cập nhật thông tin tài khoản, vai trò và trạng thái truy cập.',
    createUserDescription: 'Tài khoản do quản trị viên tạo sẽ hoạt động ngay lập tức.',
    password: 'Mật khẩu',
    cancel: 'Hủy',
    saving: 'Đang lưu...',
    saveChanges: 'Lưu thay đổi',
    deactivateUser: 'Vô hiệu hóa người dùng',
    deactivateDescription: 'Tài khoản sẽ được chuyển sang trạng thái ngưng hoạt động và không còn truy cập được hệ thống.',
    goBack: 'Quay lại',
    usernameRequired: 'Tên đăng nhập là bắt buộc.',
    usernameTooLong: 'Tên đăng nhập không được vượt quá 255 ký tự.',
    emailRequired: 'Email là bắt buộc.',
    invalidEmail: 'Định dạng email không hợp lệ.',
    phoneRequired: 'Số điện thoại là bắt buộc.',
    invalidPhone: 'Số điện thoại phải gồm 9-15 chữ số và có thể bắt đầu bằng +.',
    passwordRequired: 'Mật khẩu là bắt buộc.',
    invalidPassword: 'Mật khẩu phải có từ 6 đến 72 ký tự.',
    loadUsersError: 'Không thể tải danh sách người dùng.',
    updateUserSuccess: 'Đã cập nhật người dùng thành công.',
    createUserSuccess: 'Đã tạo người dùng thành công.',
    saveUserError: 'Không thể lưu người dùng.',
    deactivateUserSuccess: 'Đã chuyển người dùng sang trạng thái ngưng hoạt động thành công.',
    deactivateUserError: 'Không thể vô hiệu hóa người dùng.',
    joinSystem: 'Tham gia hệ thống',
    createAccount: 'Tạo tài khoản',
    registerSubtitle: 'Tài khoản mới mặc định là Spectator. Bạn có thể đăng ký trở thành Owner trong Profile sau khi đăng nhập.',
    login: 'Đăng nhập',
    backHome: 'Về trang chủ',
    registerSuccess: 'Đã tạo tài khoản thành công. Bạn có thể đăng nhập ngay.',
    registerError: 'Đăng ký thất bại. Vui lòng thử lại.',
    show: 'Hiện',
    hide: 'Ẩn',
    minPasswordPlaceholder: 'Tối thiểu 6 ký tự',
    creatingAccount: 'Đang tạo tài khoản...',
    alreadyHaveAccount: 'Đã có tài khoản?',
    welcomeBack: 'Chào mừng trở lại',
    loginSubtitle: 'Nhập thông tin tài khoản để tiếp tục.',
    loginError: 'Đăng nhập thất bại. Vui lòng thử lại.',
    rememberLogin: 'Ghi nhớ đăng nhập',
    signingIn: 'Đang đăng nhập...',
    noAccount: 'Chưa có tài khoản?',
    horseSystem: 'Hệ thống đua ngựa',
    horseRace: 'Giải đua ngựa',
    authHeadline: 'Mỗi cuộc đua bắt đầu từ một vạch xuất phát được quản lý tốt.',
    authDescription: 'Đăng nhập để quản lý giải đấu, ngựa, đơn đăng ký, phân công cuộc đua và kết quả chính thức.',
    featureOperations: 'Vận hành giải đấu',
    featureOperationsDescription: 'Quản lý lịch trình, vòng đấu, cuộc đua và đơn đăng ký.',
    featureVerified: 'Người tham gia được xác minh',
    featureVerifiedDescription: 'Kết nối owner, jockey, admin và referee.',
    featureRaceReady: 'Sẵn sàng cho ngày thi đấu',
    featureRaceReadyDescription: 'Phân công suất thi đấu và theo dõi từng sự kiện đến khi kết thúc.'
  },
  en: {
    wallet: 'Wallet',
    walletDescription: 'Balance and top-ups',
    walletAccess: 'Wallet access',
    walletAccessDenied: 'Access denied',
    walletTopupsUnavailable: 'Wallet top-ups are not available for this account.',
    walletCurrentBalance: 'Current balance',
    walletBalanceDescription: 'Track the wallet balance for this {{role}} account.',
    walletGenericUser: 'user',
    walletBalance: 'Balance',
    walletTopUp: 'Top up',
    walletTopUpWithProvider: 'Top up with {{provider}}',
    walletEnterTopUpAmount: 'Enter top-up amount',
    walletPaymentThroughProvider: 'Payment will be processed through {{provider}}.',
    walletAmount: 'Amount',
    walletEnterAmount: 'Enter amount',
    walletPaymentMethod: 'Payment method',
    walletTotal: 'Total',
    walletRedirecting: 'Redirecting...',
    walletTopUpSuccessful: 'Top-up successful.',
    walletTopUpFailed: 'Top-up failed.',
    walletLoadError: 'Unable to load wallet information.',
    walletAmountGreaterThanZero: 'Amount must be greater than 0.',
    walletNoPaymentUrl: 'The top-up transaction was created, but no payment URL was returned.',
    walletCreateTopUpError: 'Unable to create the top-up transaction.',
    close: 'Close',
    loading: 'Loading',
    languageLabel: 'Language',
    vietnamese: 'Vietnamese',
    english: 'English',
    adminCenter: 'Admin Center',
    navigation: 'Navigation',
    adminArea: 'Admin Area',
    signedInAs: 'Signed in as',
    logout: 'Sign out',
    overview: 'Overview',
    overviewDescription: 'Operational status',
    manageUsers: 'User Management',
    usersDescription: 'Accounts and roles',
    manageOwners: 'Owner Management',
    ownersDescription: 'Owner applications',
    tournament: 'Tournament',
    tournamentDescription: 'Events and registration',
    manageJockeys: 'Jockey Management',
    jockeysDescription: 'Athlete profiles',
    manageHorses: 'Horse Management',
    horsesDescription: 'Profiles and health',
    refereeAssignments: 'Referee Assignments',
    refereeDescription: 'Referee schedules',
    raceResultReviews: 'Race Result Review',
    raceResultReviewDescription: 'Official result approvals',
    operationsCenter: 'Operations Center',
    operationsOverview: 'Operations Overview',
    operationsOverviewSubtitle: 'Track profiles, prepare race lists, and coordinate tournaments from one screen.',
    syncing: 'Syncing',
    activeAccountCount: '{{count}} active accounts',
    loadingTournaments: 'Loading tournaments',
    tournamentCount: '{{count}} tournaments',
    retry: 'Retry',
    openTournaments: 'Open tournaments',
    tournamentsInSystem: '{{count}} tournaments in the system',
    reviewQueueProfiles: 'Profiles awaiting review',
    reviewQueueProfilesNote: 'Applications, horses, and jockey profiles combined',
    raceEntryQueue: 'Waiting for race assignment',
    approvedRegistrationCount: '{{count}} approved registrations',
    assignedReferees: 'Assigned referees',
    assignedRefereesNote: 'Races already have assigned referees',
    needsProcessing: 'Needs processing',
    adminWorkQueue: 'Admin work queue',
    waitingCount: '{{count}} waiting',
    ownerApproval: 'Owner approval',
    ownerApprovalNote: 'Accounts waiting to become Owners',
    registrationApproval: 'Registration approval',
    registrationApprovalNote: 'Accepted jockey invitations waiting for admin decision',
    horseApproval: 'Horse approval',
    horseApprovalNote: 'Horse profiles and health certificates awaiting review',
    jockeyApproval: 'Jockey approval',
    jockeyApprovalNote: 'Jockey profiles awaiting approval',
    raceQueueSetup: 'Race assignment queue',
    raceQueueSetupNote: 'Confirmed registrations waiting for race assignment',
    quickActions: 'Quick actions',
    continueSetup: 'Continue setup',
    setupTournament: 'Set up tournament',
    setupTournamentNote: 'Create tournaments and their races',
    refereeAssignmentNote: '{{count}} races already have an assignee',
    activeAccountNote: '{{count}} active accounts',
    eventSchedule: 'Event schedule',
    upcomingTournaments: 'Upcoming tournaments',
    noUpcomingTournaments: 'No upcoming tournaments',
    noUpcomingTournamentsNote: 'Upcoming tournaments will appear here.',
    tournamentLifecycle: 'Tournament lifecycle',
    tournamentsByStatus: 'Tournaments by status',
    noDate: 'No date',
    notUpdated: 'Not updated',
    ownerApplicationsTitle: 'Owner Management',
    ownerApplicationsSubtitle: 'Search, filter, review, approve, and reject owner applications.',
    ownerApplicationDetail: 'Owner application detail',
    applicationNumber: 'Application #{{id}}',
    reviewOwnerApplication: 'Review submitted personal information and approve or reject the owner request.',
    backToList: 'Back to list',
    personalInformation: 'Personal information',
    submittedDate: 'Submitted {{date}}',
    fullName: 'Full name',
    dateOfBirth: 'Date of birth',
    gender: 'Gender',
    nationality: 'Nationality',
    address: 'Address',
    identityDocument: 'National ID / Passport image',
    identityAlt: 'Applicant identity document',
    rejectReason: 'Reject reason',
    approve: 'Approve',
    reject: 'Reject',
    approveOwnerApplication: 'Approve owner application',
    approveOwnerConfirm: 'Are you sure you want to approve this owner application?',
    rejectOwnerApplication: 'Reject owner application',
    rejectReasonRequired: 'Reject reason is required and will be visible to the applicant.',
    rejectReasonPlaceholder: 'Example: Identity information is invalid.',
    confirmReject: 'Confirm reject',
    processing: 'Processing...',
    ownerApplicationsLoadError: 'Unable to load owner applications.',
    ownerApplicationDetailLoadError: 'Unable to load owner application details.',
    ownerApplicationApproved: 'Application approved. User role is now Owner and OwnerProfile has been created.',
    ownerApplicationApproveError: 'Unable to approve owner application.',
    ownerApplicationRejected: 'Application rejected. User role remains Spectator.',
    ownerApplicationRejectError: 'Unable to reject owner application.',
    noOwnerApplications: 'No owner applications found',
    noOwnerApplicationsHint: 'Try changing the search keyword or status filter.',
    searchOwnerApplications: 'Search by ID, applicant, email, document image...',
    applicationId: 'Application ID',
    applicantName: 'Applicant name',
    submissionDate: 'Submission date',
    action: 'Action',
    loadingOwnerApplications: 'Loading owner applications...',
    viewDetails: 'View details',
    pageOf: 'Page {{page}} of {{total}} · {{count}} applications',
    previous: 'Previous',
    next: 'Next',
    status_OPEN_FOR_REGISTRATION: 'Open for registration',
    status_REGISTRATION_CLOSED: 'Registration closed',
    status_READY: 'Ready',
    status_IN_PROGRESS: 'In progress',
    status_PENDING_REVIEW: 'Pending result review',
    status_COMPLETED: 'Completed',
    status_CANCELLED: 'Cancelled',
    status_ACTIVE: 'Active',
    status_INACTIVE: 'Inactive',
    status_BLOCKED: 'Blocked',
    status_PENDING: 'Pending',
    status_APPROVED: 'Approved',
    status_REJECTED: 'Rejected',
    status_UNDER_REVIEW: 'Under review',
    role_ADMIN: 'Admin',
    role_OWNER: 'Owner',
    role_JOCKEY: 'Jockey',
    role_REFEREE: 'Referee',
    role_SPECTATOR: 'Spectator',
    admin: 'Admin',
    userManagementTitle: 'User Management',
    userManagementSubtitle: 'Manage account information, roles, and access status.',
    refresh: 'Refresh',
    totalUsers: 'Total users',
    activeUsers: 'Active',
    inactiveBlocked: 'Inactive / Blocked',
    userList: 'User list',
    userCount: '{{filtered}} / {{total}} users',
    createUser: 'Create user',
    searchUsers: 'Search by username, email, or phone number',
    allRoles: 'All roles',
    allStatuses: 'All',
    id: 'ID',
    username: 'Username',
    email: 'Email',
    phone: 'Phone number',
    role: 'Role',
    status: 'Status',
    actions: 'Actions',
    loadingUsers: 'Loading users...',
    noUsersFound: 'No users found.',
    edit: 'Edit',
    deactivate: 'Deactivate',
    newAccount: 'New account',
    userNumber: 'User #{{id}}',
    editUser: 'Edit user',
    createUserTitle: 'Create user',
    editUserDescription: 'Update account information, role, and access status.',
    createUserDescription: 'Accounts created by administrators are active immediately.',
    password: 'Password',
    cancel: 'Cancel',
    saving: 'Saving...',
    saveChanges: 'Save changes',
    deactivateUser: 'Deactivate user',
    deactivateDescription: 'This account will be changed to inactive and can no longer access the system.',
    goBack: 'Go back',
    usernameRequired: 'Username is required.',
    usernameTooLong: 'Username cannot exceed 255 characters.',
    emailRequired: 'Email is required.',
    invalidEmail: 'Email format is invalid.',
    phoneRequired: 'Phone number is required.',
    invalidPhone: 'Phone must be 9-15 digits and may start with +.',
    passwordRequired: 'Password is required.',
    invalidPassword: 'Password must be 6 to 72 characters.',
    loadUsersError: 'Unable to load users.',
    updateUserSuccess: 'User updated successfully.',
    createUserSuccess: 'User created successfully.',
    saveUserError: 'Unable to save user.',
    deactivateUserSuccess: 'User changed to inactive successfully.',
    deactivateUserError: 'Unable to deactivate user.',
    joinSystem: 'Join the system',
    createAccount: 'Create account',
    registerSubtitle: 'New accounts default to Spectator. You can apply to become an Owner from Profile after signing in.',
    login: 'Login',
    backHome: 'Back home',
    registerSuccess: 'Account created successfully. You can sign in now.',
    registerError: 'Registration failed. Please try again.',
    show: 'Show',
    hide: 'Hide',
    minPasswordPlaceholder: 'Minimum 6 characters',
    creatingAccount: 'Creating account...',
    alreadyHaveAccount: 'Already have an account?',
    welcomeBack: 'Welcome back',
    loginSubtitle: 'Enter your account information to continue.',
    loginError: 'Login failed. Please try again.',
    rememberLogin: 'Remember me',
    signingIn: 'Signing in...',
    noAccount: "Don't have an account?",
    horseSystem: 'Horse Racing System',
    horseRace: 'Horse racing',
    authHeadline: 'Every race starts from a well-managed starting line.',
    authDescription: 'Sign in to manage tournaments, horses, applications, race assignments, and official results.',
    featureOperations: 'Tournament operations',
    featureOperationsDescription: 'Manage schedules, rounds, races, and applications.',
    featureVerified: 'Verified participants',
    featureVerifiedDescription: 'Connect owners, jockeys, admins, and referees.',
    featureRaceReady: 'Race-day ready',
    featureRaceReadyDescription: 'Assign race slots and track every event through completion.'
  }
};

const LanguageContext = createContext(null);

function getInitialLanguage() {
  if (typeof window === 'undefined') return DEFAULT_LANGUAGE;
  const stored = window.localStorage.getItem(STORAGE_KEY);
  return stored === 'en' || stored === 'vi' ? stored : DEFAULT_LANGUAGE;
}

function interpolate(template, params) {
  return Object.entries(params || {}).reduce(
    (text, [key, value]) => text.replaceAll(`{{${key}}}`, String(value)),
    template
  );
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => {
    function t(key, params) {
      const template = translations[language]?.[key] || translations[DEFAULT_LANGUAGE]?.[key] || key;
      return interpolate(template, params);
    }

    return {
      language,
      setLanguage,
      toggleLanguage: () => setLanguage((current) => (current === 'vi' ? 'en' : 'vi')),
      t
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
