/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpectatorIndexRouteImport } from './routes/spectator/index'
import { Route as RefereeIndexRouteImport } from './routes/referee/index'
import { Route as OwnerIndexRouteImport } from './routes/owner/index'
import { Route as JockeyIndexRouteImport } from './routes/jockey/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SpectatorPredictionsRouteImport } from './routes/spectator/predictions'
import { Route as SpectatorLeaderboardRouteImport } from './routes/spectator/leaderboard'
import { Route as OwnerRegisterRouteImport } from './routes/owner/register'
import { Route as OwnerHorsesRouteImport } from './routes/owner/horses'
import { Route as JockeyScheduleRouteImport } from './routes/jockey/schedule'
import { Route as JockeyInvitationsRouteImport } from './routes/jockey/invitations'
import { Route as AdminTournamentsRouteImport } from './routes/admin/tournaments'
import { Route as AdminRegistrationsRouteImport } from './routes/admin/registrations'
import { Route as AdminRacesRouteImport } from './routes/admin/races'
import { Route as AdminPrizesRouteImport } from './routes/admin/prizes'
import { Route as AdminLeaderboardRouteImport } from './routes/admin/leaderboard'
import { Route as RefereeInspectRaceIdRouteImport } from './routes/referee/inspect.$raceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectatorIndexRoute = SpectatorIndexRouteImport.update({
  id: '/spectator/',
  path: '/spectator/',
  getParentRoute: () => rootRouteImport,
} as any)
const RefereeIndexRoute = RefereeIndexRouteImport.update({
  id: '/referee/',
  path: '/referee/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const JockeyIndexRoute = JockeyIndexRouteImport.update({
  id: '/jockey/',
  path: '/jockey/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectatorPredictionsRoute = SpectatorPredictionsRouteImport.update({
  id: '/spectator/predictions',
  path: '/spectator/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectatorLeaderboardRoute = SpectatorLeaderboardRouteImport.update({
  id: '/spectator/leaderboard',
  path: '/spectator/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRegisterRoute = OwnerRegisterRouteImport.update({
  id: '/owner/register',
  path: '/owner/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerHorsesRoute = OwnerHorsesRouteImport.update({
  id: '/owner/horses',
  path: '/owner/horses',
  getParentRoute: () => rootRouteImport,
} as any)
const JockeyScheduleRoute = JockeyScheduleRouteImport.update({
  id: '/jockey/schedule',
  path: '/jockey/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const JockeyInvitationsRoute = JockeyInvitationsRouteImport.update({
  id: '/jockey/invitations',
  path: '/jockey/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/admin/tournaments',
  path: '/admin/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/admin/registrations',
  path: '/admin/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRacesRoute = AdminRacesRouteImport.update({
  id: '/admin/races',
  path: '/admin/races',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrizesRoute = AdminPrizesRouteImport.update({
  id: '/admin/prizes',
  path: '/admin/prizes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/admin/leaderboard',
  path: '/admin/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RefereeInspectRaceIdRoute = RefereeInspectRaceIdRouteImport.update({
  id: '/referee/inspect/$raceId',
  path: '/referee/inspect/$raceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/prizes': typeof AdminPrizesRoute
  '/admin/races': typeof AdminRacesRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/jockey/invitations': typeof JockeyInvitationsRoute
  '/jockey/schedule': typeof JockeyScheduleRoute
  '/owner/horses': typeof OwnerHorsesRoute
  '/owner/register': typeof OwnerRegisterRoute
  '/spectator/leaderboard': typeof SpectatorLeaderboardRoute
  '/spectator/predictions': typeof SpectatorPredictionsRoute
  '/admin/': typeof AdminIndexRoute
  '/jockey/': typeof JockeyIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/referee/': typeof RefereeIndexRoute
  '/spectator/': typeof SpectatorIndexRoute
  '/referee/inspect/$raceId': typeof RefereeInspectRaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/prizes': typeof AdminPrizesRoute
  '/admin/races': typeof AdminRacesRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/jockey/invitations': typeof JockeyInvitationsRoute
  '/jockey/schedule': typeof JockeyScheduleRoute
  '/owner/horses': typeof OwnerHorsesRoute
  '/owner/register': typeof OwnerRegisterRoute
  '/spectator/leaderboard': typeof SpectatorLeaderboardRoute
  '/spectator/predictions': typeof SpectatorPredictionsRoute
  '/admin': typeof AdminIndexRoute
  '/jockey': typeof JockeyIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/referee': typeof RefereeIndexRoute
  '/spectator': typeof SpectatorIndexRoute
  '/referee/inspect/$raceId': typeof RefereeInspectRaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/prizes': typeof AdminPrizesRoute
  '/admin/races': typeof AdminRacesRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/jockey/invitations': typeof JockeyInvitationsRoute
  '/jockey/schedule': typeof JockeyScheduleRoute
  '/owner/horses': typeof OwnerHorsesRoute
  '/owner/register': typeof OwnerRegisterRoute
  '/spectator/leaderboard': typeof SpectatorLeaderboardRoute
  '/spectator/predictions': typeof SpectatorPredictionsRoute
  '/admin/': typeof AdminIndexRoute
  '/jockey/': typeof JockeyIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/referee/': typeof RefereeIndexRoute
  '/spectator/': typeof SpectatorIndexRoute
  '/referee/inspect/$raceId': typeof RefereeInspectRaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/leaderboard'
    | '/admin/prizes'
    | '/admin/races'
    | '/admin/registrations'
    | '/admin/tournaments'
    | '/jockey/invitations'
    | '/jockey/schedule'
    | '/owner/horses'
    | '/owner/register'
    | '/spectator/leaderboard'
    | '/spectator/predictions'
    | '/admin/'
    | '/jockey/'
    | '/owner/'
    | '/referee/'
    | '/spectator/'
    | '/referee/inspect/$raceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/leaderboard'
    | '/admin/prizes'
    | '/admin/races'
    | '/admin/registrations'
    | '/admin/tournaments'
    | '/jockey/invitations'
    | '/jockey/schedule'
    | '/owner/horses'
    | '/owner/register'
    | '/spectator/leaderboard'
    | '/spectator/predictions'
    | '/admin'
    | '/jockey'
    | '/owner'
    | '/referee'
    | '/spectator'
    | '/referee/inspect/$raceId'
  id:
    | '__root__'
    | '/'
    | '/admin/leaderboard'
    | '/admin/prizes'
    | '/admin/races'
    | '/admin/registrations'
    | '/admin/tournaments'
    | '/jockey/invitations'
    | '/jockey/schedule'
    | '/owner/horses'
    | '/owner/register'
    | '/spectator/leaderboard'
    | '/spectator/predictions'
    | '/admin/'
    | '/jockey/'
    | '/owner/'
    | '/referee/'
    | '/spectator/'
    | '/referee/inspect/$raceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminPrizesRoute: typeof AdminPrizesRoute
  AdminRacesRoute: typeof AdminRacesRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminTournamentsRoute: typeof AdminTournamentsRoute
  JockeyInvitationsRoute: typeof JockeyInvitationsRoute
  JockeyScheduleRoute: typeof JockeyScheduleRoute
  OwnerHorsesRoute: typeof OwnerHorsesRoute
  OwnerRegisterRoute: typeof OwnerRegisterRoute
  SpectatorLeaderboardRoute: typeof SpectatorLeaderboardRoute
  SpectatorPredictionsRoute: typeof SpectatorPredictionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  JockeyIndexRoute: typeof JockeyIndexRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  RefereeIndexRoute: typeof RefereeIndexRoute
  SpectatorIndexRoute: typeof SpectatorIndexRoute
  RefereeInspectRaceIdRoute: typeof RefereeInspectRaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectator/': {
      id: '/spectator/'
      path: '/spectator'
      fullPath: '/spectator/'
      preLoaderRoute: typeof SpectatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referee/': {
      id: '/referee/'
      path: '/referee'
      fullPath: '/referee/'
      preLoaderRoute: typeof RefereeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jockey/': {
      id: '/jockey/'
      path: '/jockey'
      fullPath: '/jockey/'
      preLoaderRoute: typeof JockeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectator/predictions': {
      id: '/spectator/predictions'
      path: '/spectator/predictions'
      fullPath: '/spectator/predictions'
      preLoaderRoute: typeof SpectatorPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectator/leaderboard': {
      id: '/spectator/leaderboard'
      path: '/spectator/leaderboard'
      fullPath: '/spectator/leaderboard'
      preLoaderRoute: typeof SpectatorLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/register': {
      id: '/owner/register'
      path: '/owner/register'
      fullPath: '/owner/register'
      preLoaderRoute: typeof OwnerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/horses': {
      id: '/owner/horses'
      path: '/owner/horses'
      fullPath: '/owner/horses'
      preLoaderRoute: typeof OwnerHorsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jockey/schedule': {
      id: '/jockey/schedule'
      path: '/jockey/schedule'
      fullPath: '/jockey/schedule'
      preLoaderRoute: typeof JockeyScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jockey/invitations': {
      id: '/jockey/invitations'
      path: '/jockey/invitations'
      fullPath: '/jockey/invitations'
      preLoaderRoute: typeof JockeyInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/admin/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/admin/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/races': {
      id: '/admin/races'
      path: '/admin/races'
      fullPath: '/admin/races'
      preLoaderRoute: typeof AdminRacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/prizes': {
      id: '/admin/prizes'
      path: '/admin/prizes'
      fullPath: '/admin/prizes'
      preLoaderRoute: typeof AdminPrizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/admin/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referee/inspect/$raceId': {
      id: '/referee/inspect/$raceId'
      path: '/referee/inspect/$raceId'
      fullPath: '/referee/inspect/$raceId'
      preLoaderRoute: typeof RefereeInspectRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminPrizesRoute: AdminPrizesRoute,
  AdminRacesRoute: AdminRacesRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminTournamentsRoute: AdminTournamentsRoute,
  JockeyInvitationsRoute: JockeyInvitationsRoute,
  JockeyScheduleRoute: JockeyScheduleRoute,
  OwnerHorsesRoute: OwnerHorsesRoute,
  OwnerRegisterRoute: OwnerRegisterRoute,
  SpectatorLeaderboardRoute: SpectatorLeaderboardRoute,
  SpectatorPredictionsRoute: SpectatorPredictionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  JockeyIndexRoute: JockeyIndexRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  RefereeIndexRoute: RefereeIndexRoute,
  SpectatorIndexRoute: SpectatorIndexRoute,
  RefereeInspectRaceIdRoute: RefereeInspectRaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
